name: Build and test GAM

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '37 22 * * *'

defaults:
  run:
    shell: bash

env:
  BUILD_PYTHON_VERSION: "3.9.0"
  MIN_PYTHON_VERSION: "3.9.0"
  BUILD_OPENSSL_VERSION: "1.1.1h"
  MIN_OPENSSL_VERSION: "1.1.1h"
  PATCHELF_VERSION: "0.11"
  PYINSTALLER_COMMIT: "5bc2c4620bfc5dde5a76a007c7ff50ee74223ca5"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019, windows-2016]
    continue-on-error: true
    steps:

      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Before Build
        run: |
             if [ "${RUNNER_OS}" == "macOS" ]; then
               export GAMOS="macos"
             else
               export GAMOS=$"${RUNNER_OS,,}"
             if [ "${ImageOS}" == "win16" ]; then
               export PLATFORM="x86";
             else
               export PLATFORM="x86_64"
             fi
             cd src
             source travis/${GAMOS}-before-install.sh
