name: Build and test GAM

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '37 22 * * *'

defaults:
  run:
    shell: bash
    default-directory: ..

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019, windows-2016]
    steps:
      - name: Before Build
        run: |
             export GAMOS=$"${RUNNER_OS,,}"
             if [ "${ImageOS}" == "win16" ]; then
               export PLATFORM="x86";
             else
               export PLATFORM="x86_64"
             fi
             echo "pwd"
             pwd
             echo "ls"
             ls -al
             source travis/${GAMOS}-before-install.sh
